<Project ToolsVersion="15.0">
  <!--
    Central package version management for the SunTime solution.

    To update the version of Uno, update the Sdk version in global.json instead.
    See https://aka.platform.uno/using-uno-sdk for more information.
    See https://aka.platform.uno/using-uno-sdk#implicit-packages for details on
    implicit packages managed by the Uno SDK.
  -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.7.0" />
  </ItemGroup>
</Project>
